"""Utilities module for Contract Management API"""

from .prompts import (
    CONTRACT_EXTRACTION_PROMPT,
    SIMILAR_SERVICE_SEARCH_PROMPT,
    REPORT_GENERATION_PROMPT,
    FILE_CONTENT_EXTRACTION_PROMPT,
    DATA_VALIDATION_PROMPT,
    VISION_CONTRACT_EXTRACTION_PROMPT,
)

__all__ = [
    "CONTRACT_EXTRACTION_PROMPT",
    "SIMILAR_SERVICE_SEARCH_PROMPT",
    "REPORT_GENERATION_PROMPT",
    "FILE_CONTENT_EXTRACTION_PROMPT",
    "DATA_VALIDATION_PROMPT",
    "VISION_CONTRACT_EXTRACTION_PROMPT",
]
